[package]
name = "clf-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"

clf-semantic-analysis = {path = "./sea"}
clf-ast = {path = "./ast"}